version: 0.2
phases:
  install:
    on-failure: ABORT
    commands:
      - npm install
  build:
    on-failure: ABORT
    commands:
      - npm run build
      - cp appspec.yml build/
      - cp -r scripts build/scripts 
      - ls -R
artifacts:
  files:
    - appspec.yml
    - public/*
    - scripts/*
    - ./*
  base-directory: 'build'
