version: 0.2
phases:
  install:
    on-failure: ABORT
    commands:
      - npm install
  build:
    on-failure: ABORT
    commands:
      - npm run build
      - cp appspec.yml build/
      - cp -r scripts build/scripts 
artifacts:
  files:
    - appspec.yml
    - scripts/*
    - index.html
    - static/css/*
    - static/js/*
    - static/media/*
    - asset-manifest.json
    - favicon.ico
    - logo192.png
    - logo512.png
    - manifest.json  
    - ./*
  base-directory: 'build'
